# This docker-compose file is not designed to run services
# Usage:
#   sudo docker-compose -f docker/production/production.build.yml build
#   sudo docker-compose -f docker/production/production.build.yml push

version: "3.6"

services:
  production:
    image: besouro/app:production
    build:
      args:
        api_host: api.besouro.ejplatform.org
      context: ../../
      dockerfile: ./docker/production/Dockerfile
