apiVersion: v1
kind: Service
metadata:
  name: besouro-app
  labels:
    app: besouro
spec:
  type: NodePort
  selector:
    app: besouro
    tier: app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: besouro-app
  labels:
    app: besouro
spec:
  selector:
    matchLabels:
      app: besouro
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: besouro
        tier: app
    spec:
      containers:
      - image: besouro/app:staging
        name: app
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
          name: app
