# This docker-compose file is not designed to run services
# Usage:
#   sudo docker-compose -f docker/develop/build.yml build
#   sudo docker-compose -f docker/develop/build.yml push

version: "3.6"

services:
  development:
    image: besouro/app:dev
    build:
      context: ../../
      dockerfile: ./docker/develop/Dockerfile
      cache_from:
        - besouro/app:dev
